### ISSUE TITLE
pa11y-reporter-html 2.x does not support pa11y 5.3

### ISSUE THREAD

**Issue by skorasaurus** [pa11y/pa11y-reporter-html#10]
I'm not sure if you're still supporting 5.x of pa11y (the readme says yes), but installing from the npm gives me incompatible packages. 

To reproduce: 

1. `npm install -g pa11y` installs a version of 5.3.0. 
2. `npm install -g pa11y-reporter-html`  installs pa11y-reporter-html@2.0.0
3. run an example , e.g. `pa11y -e axe --reporter html https://url.com > ~/2020-09-11-book.html`

receive message :

> Error: The installed "html" reporter does not support Pa11y 5.3.0
> Please update your version of Pa11y or the reporter
> Reporter Support: ^6.0.0 || ^6.0.0-alpha || ^6.0.0-beta
> Pa11y Version:    5.3.0

other notes, ubuntu 18.04; node v12.18.2, npm@6.14.5, nvm v0.33.11

**Comment by josebolos** [comment]
Hi @skorasaurus!

That's correct, version 2 of `pa11y-reporter-html` is compatible with the upcoming version 6 of `pa11y`.

If you're using the stable version of `pa11y` (`5.3.0` at the time of writing) you will need to use version `1.x` of `pa11y-reporter-html`.

I hope that it helps! Let us know if it doesn't.
