### ISSUE TITLE
Error: The installed "html" reporter does not support Pa11y 5.3.1

### ISSUE THREAD

**Issue by Mac944** [pa11y/pa11y-reporter-html#12]
Receiving the following error, have the latest versions of Pa11y and reporter...

Error: The installed "html" reporter does not support Pa11y 5.3.1
Please update your version of Pa11y or the reporter
Reporter Support: ^6.0.0 || ^6.0.0-alpha || ^6.0.0-beta
Pa11y Version:    5.3.1

**Comment by josebolos** [comment]
Hi @Mac944,

Thanks for creating this issue. Although it's not specified in the documentation, if you using a stable version of `pa11y` (like for example 5.3.1) you will need to use v1 of this reporter.

Version 2 of the html reporter is compatible only with `pa11y` v6, which is currently still in alpha stage.

I've created #13 to improve the documentation and make this clearer.

I'm closing this issue but please feel free to reopen it if this doesn't fix your problem.
