### ISSUE TITLE
Unable to test different "pages" if URL is the same

### ISSUE THREAD

**Issue by wblanchard-mckinsey** [pa11y/pa11y-reporter-html#16]
We have three "pages" that all share the same URL (different divs are enabled or disabled based on selections).  This means that the only test that will be in the file is the last one as each test will overwrite the previous test using the URL as the file name.

example .pa11yci
```
{
  "defaults": {
   "standard": "WCAG2AA",
   "reporters": ["pa11y-ci-reporter-html", { "destination": "./reports", "includeZeroIssues": true }]
},
  "urls": [
    {
      "url": "https://mypages.com/myfirstpage.html",
        "actions": [
          "wait for element #myelement1 to be added",
          "click element #submit1",
          "wait for path to be /mysecondpage.html"
        ]
    },
    {
      "url": "https://mypages.com/myfirstpage.html",
        "actions": [
          "wait for element #myelement1 to be added",
          "click element #submit1",
          "wait for path to be /mysecondpage.html"
          "wait for element .mynextbutton to be added",
          "click element .mynextbutton",
          "wait for #infoWrapper to be added"
        ]
    },        
  ]
}

**Comment by josebolos** [comment]
Hi @wblanchard-mckinsey,

Thanks for creating this issue. You seem to be using the `pa11y-ci-reporter-html`, which is not part of the pa11y project and it's hosted at https://gitlab.com/gitlab-ci-utils/pa11y-ci-reporter-html/

If you find an issue that is specific to `pa11y-ci` please feel free to report the issue at https://github.com/pa11y/pa11y-ci
