### ISSUE TITLE
Compatibility with Pa11y-ci

### ISSUE THREAD

**Issue by victorjkhalaf** [pa11y/pa11y-reporter-html#17]
Although the readme clearly shows the html reporter is supported https://github.com/pa11y/pa11y-ci#reporters, I just can't get it to output using `pa11y-ci -c "config.json"   > ./report.html `

where config.json is 
```json
{
  "defaults": {
    "chromeLaunchConfig": {
      "args": [
        "--no-sandbox"
      ]
    },
    "reporters": [
      "pa11y-reporter-html"
    ]
  },
  "urls": [
    "https://www.canvaspop.com/"
  ]
}
```

It dumps a blank html file. It works when I use the json or cli reporters however.
My package.json has this as dependencies

```
 "dependencies": {
    "pa11y-ci": "^3.0.1",
    "pa11y-reporter-html": "^2.0.0"
  }
```
I've tried variations like using the CLI version --reporter=pa11y-reporter-html.

I'm currently just testing this locally before I push up to BuildKite with the Dockerfile using the buildkite/puppeteer image.

Am I missing anything?

**Comment by josebolos** [comment]
Hi @wblanchard-mckinsey,

Thanks for creating this issue. You seem to be using the `pa11y-ci-reporter-html`, which is not part of the pa11y project and it's hosted at https://gitlab.com/gitlab-ci-utils/pa11y-ci-reporter-html/

This repo is for the `pa11y-reporter-html`, which only works with pa11y and not `pa11y-ci`. If you find an issue that is specific to `pa11y` or `pa11y-ci` please feel free to report the issue at https://github.com/pa11y/pa11y or https://github.com/pa11y/pa11y-ci

**Comment by victorjkhalaf** [comment]
I think you were responding to the wrong person and for the wrong reasons.
I was not using that particular project, but you inadvertently pointed me in the right direction to use it.

I will say however your pa11y-ci documentation is misleading. 
On https://github.com/pa11y/pa11y-ci#reporters there are commands explicitly pointing to the wrong html reporter project which is what caused this issue to be raised:
```
npm install pa11y-reporter-html --save
pa11y-ci --reporter=pa11y-reporter-html https://pa11y.org/
```
